name: branch workflow

on:
  push:
    # push on all branches
  create:
  delete:  

jobs:
  master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event.ref_type != 'branch'
    env:
      ENVIRONMENT_NAME: prod
    steps: 
      - name: deploy application to production
        run: |
          echo "kubectl create namespace ${ENVIRONMENT_NAME}"      

  branch:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && contains(github.event.head_commit.message, '#DEPLOY') && github.ref != 'refs/heads/master'
    env:
      ENVIRONMENT_NAME: ${{github.event.ref}}
    steps: 
      - name: Set BRANCH value
        id: step_one
        run: |
          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME##*/}" >> $GITHUB_ENV
      - name: deploy application to new branch
        if: github.event_name == 'create' || github.ref != 'refs/heads/master'
        run: |
          echo "kubectl create namespace ${ENVIRONMENT_NAME}"    

      - name: Delete application from removed branch
        if: github.event_name == 'delete'
        run: |
          echo "kubectl delete namespace ${ENVIRONMENT_NAME}"
          