name: Context workflow

on:
  push:
    # Only run on the master branch.
  # Add gcp-prototype as new target branch to trigger build/test, will remove when modernization is done
    branches: [master]
    # Ignore files that we want people to update aggressively without worrying
    # about builds or deploys. Also ignore `libs`, which has its own CI tasks.
    paths-ignore:
      - '.github/CODEOWNERS'
      - '**/README.md'
      - 'docs/**'
      - 'libs/ts/**'
      - 'libs/java/**'
      - 'workers/**'
  pull_request:
    # Only run on pull requests against master.
    # Add gcp-prototype as new target branch to trigger build/test, will remove when modernization is done
    branches: [master,gcp-prototype]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '**/README.md'
      - 'docs/**'
      - 'libs/ts/**'
      - 'libs/java/**'
      - 'workers/**'

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"