# by default it will be triggered on three different types of activities: 
# opened, synchronize, and reopened..

name: Pull Request Workflow
on: [push, pull_request]

jobs:
  pul-request:
    if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request' && contains(github.event.pull_request.body,'#DEPLOY') && ( github.event.action == 'opened' || github.event.action == 'synchronize' )
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{github.head_ref}}
    steps: 
      - name: Get BRANCH value
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#DEPLOY')
        id: step_one
        run: |
          BRANCH_REF=${{github.ref}}
          echo "ENVIRONMENT_NAME=${BRANCH_REF##*/}" >> $GITHUB_ENV
      - name: deploy application to new branch
        run: |
          echo "kubectl create namespace ${ENVIRONMENT_NAME}"    


      - name: Delete application from removed branch
        if: github.event_name == 'delete'
        run: |
          echo "kubectl delete namespace ${ENVIRONMENT_NAME}"
