# by default it will be triggered on three different types of activities: 
# opened, synchronize, and reopened.

name: Pull Request Workflow
on: [push, pull_request]

jobs:
  pul-request:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.body == '#DEPLOY') &&
      (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{github.head_ref}}
    steps: 
      - name: Set BRANCH value
        id: step_one
        run: |
          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME##*/}" >> $GITHUB_ENV
      - name: deploy application to new branch
        run: |
          echo "kubectl create namespace ${ENVIRONMENT_NAME}"    
  