# by default it will be triggered on three different types of activities: 
# opened, synchronize, and reopened.

name: Pull Request Workflow
on: [push, pull_request]

jobs:
  pul-request:
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.body == '#DEPLOY') ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, '#DEPLOY'))
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{github.head_ref}}
    steps: 
      - name: Set BRANCH value
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '#DEPLOY')
        id: step_one
        run: |
          echo "ENVIRONMENT_NAME=${{github.ref}}" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME##*/}" >> $GITHUB_ENV
      - name: deploy application to new branch
        run: |
          echo "kubectl create namespace ${ENVIRONMENT_NAME}"    
#DEPLOY-test1  
#echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME##*/}" >> $GITHUB_ENV